dependencies:
- name: dp-racs
  repository: http://jenkins-x-chartmuseum:8080
  version: 2019.9.2
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: jx-boot-python-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: python-http-qs
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: python-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
